version: 2
updates:
  - package-ecosystem: "yarn"
    schedule:
      interval: "daily"
    directory: "/"
    schedule-preset: "daily"
    labels:
      - "dependabot"
      - "react-native"
      - "expo"
    ignore:
      - dependency-name: "expo"
    open-pull-request-if-necessary: true
