version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"

  # Maintain dependencies for yarn
  - package-ecosystem: "yarn"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
